name: Checkout Repositories
on: 
  workflow_dispatch:
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-data: ${{ steps.convert-csv.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert CSV to JSON
        id: convert-csv
        shell: bash
        run: |
          csv_file="BranchSwitchListTest.csv"
          matrix_json="{\"include\":["
          first_line=true
  
          while IFS=, read -r repository path ref; do
            if [ "$first_line" = true ]; then
              first_line=false
              continue  # Skip the header line
            fi
            
            # Append to the matrix JSON string
            matrix_json="${matrix_json}{\"repo\":\"$repo\",\"ref\":\"$ref\",\"path\":\"$path\"},"
          done < "$csv_file"
  
          # # Remove the last comma and close the JSON array
          # matrix_json="${matrix_json%,}]}"
          
          # # Save the matrix JSON to the environment
          # echo "matrix-data=$matrix_json" >> $GITHUB_ENV

          matrix_json="${matrix_json%,}]}"
          echo "::set-output name=matrix-data::$matrix_json"

  checkout:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-data).include }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.path }}
          ref: ${{ matrix.ref }}
