name: Checkout Repositories
on: 
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-data: ${{ steps.prepare-matrix.outputs.matrix-data }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert CSV to JSON
        id: prepare-matrix
        shell: bash
        run: |
          csv_file="BranchSwitchListTest.csv"
          matrix_json="["
          first_line=true

          while IFS=, read -r repository path ref; do
            if [ "$first_line" = true ]; then
              first_line=false
              continue  # Skip the header line
            fi

            matrix_json="${matrix_json}{\"repo\":\"$repo\",\"ref\":\"$ref\",\"path\":\"$path\"},"
          done < "$csv_file"

          matrix_json="${matrix_json%,}]"
          echo "matrix-data=$matrix_json" >> $GITHUB_OUTPUT
      - name: Debug Matrix
        run: echo "${{ toJson(matrix.repo-matrix) }}"

        
  checkout:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: 
        repo-matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-data) }}
    steps:
      - name: Checkout Repository
        uses: viveena30/checkout_test@main
        with:
          repository: ${{ matrix.repo-matrix.repo }}
          ref: ${{ matrix.repo-matrix.ref }}
          path: ${{ matrix.repo-matrix.path }}
