name: Checkout Repositories
on: 
  workflow_dispatch:
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-data: ${{ steps.convert-csv.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert CSV to JSON
        id: convert-csv
        shell: python
        run: |
          import csv, json
          csv_file = 'BranchSwitchListTest.csv'
          matrix = []
          with open(csv_file, mode='r') as file:
              csv_reader = csv.DictReader(file)
              for row in csv_reader:
                  matrix.append({
                      'repository': row['repo'],
                      'ref': row['ref'],
                      'path': row['path']
                  })

          matrix_json = json.dumps({"include": matrix})
          
          # Save the matrix as an output of this step
          # print(f"::set-output name=matrix::{matrix_json}")
          # echo "matrix-data=${matrix_json}" >> $GITHUB_ENV

          # Save the matrix as an environment variable for output
          with open(os.environ['GITHUB_ENV'], 'a') as env_file:
              env_file.write(f"matrix-data={matrix_json}\n")
  checkout:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-data).include }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.path }}
          ref: ${{ matrix.ref }}
