name: Checkout Repositories

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-data: ${{ steps.convert-csv.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert CSV to JSON
        id: convert-csv
        run: |
          import csv, json

          csv_file = 'BranchSwitchListTest.csv'
          matrix = []

          with open(csv_file, mode='r') as file:
              csv_reader = csv.DictReader(file)
              for row in csv_reader:
                  matrix.append({
                      'repository': row['repo'],
                      'ref': row['ref'],
                      'path': row['path']
                  })

          matrix_json = json.dumps({"include": matrix})
          # Save matrix to file for debugging
          with open('matrix.json', 'w') as json_file:
              json_file.write(matrix_json)
          
          # Output the matrix using the new syntax
          echo "matrix=${matrix_json}" >> $GITHUB_ENV

  checkout:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(env.matrix).include }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.path }}
          ref: ${{ matrix.ref }}
