name: Checkout Repositories
on:
  workflow_dispatch:
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-data: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert CSV to JSON
        shell: python
        id: convert-csv
        run: |
          import csv, json
          import os

          csv_file = 'BranchSwitchListTest.csv'
          matrix = []
          with open(csv_file, mode='r') as file:
              csv_reader = csv.reader(file)
              next(csv_reader)  # Skip the header line
              
              for row in csv_reader:
                  if len(row) == 3:  # Ensure the row has all required columns
                      matrix.append({
                          'repository': row[0],
                          'path': row[1],
                          'ref': row[2]
                      })
          
          print(f"::set-output name=matrix::{json.dumps({'include': matrix})}")
  checkout:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix-data).include}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.path }}
          ref: ${{ matrix.ref }}
