name: Two Jobs Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Hello World
        run: echo "Hello, World! From Job 1"
      - name: print readme contents
        run: cat "../../README.md"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Job 2 Message
        run: echo "Hello, World! From Job 2"
